### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by mirabilos** [tomato42/ecpp-verifier#48]
The readme only ever mentions `-m modulifile` for verification, but https://www.redhat.com/en/blog/understanding-and-verifying-security-diffie-hellman-parameters has the user run `-v -m modulifile`.

When exactly do we need this, and what’s the difference?

My use case is to check whether the moduli I generated are good (or rather, if there are any bad lines, and if so, which, so I can remove them). I have so far run `-m modulifile` run once, found missing primes, ran Primo, and am now verifying the Primo outfiles. I would then move all outfiles that pass both tests (prime and not SNFS) to `src/ecpp/certificates/myname/` and then run… what exactly, with `-v`? If so, why is this not in the README? If not, what is `-v` for?

**Comment by tomato42** [comment]
The help message explains the `-v` option:
https://github.com/tomato42/ecpp-verifier/blob/8a57818f389711c58106cfe15196966752fa1538/ecpp#L320

Using `-m modulifile` just checks if primality certificates for the primes in the moduli file exist. `-v -m modulifile` also verifies the primality certificates. You need to do the latter if you don't trust the source of the primality certificates (haven't verified those primality certificates yourself).

If you generated the primality certificates with Primo, it's much quicker to use `parallel` to verify them that to use `-v`, so that's why it's not explained in the README.

Or in other words, README is supposed to explain only the most common use cases, not to be a comprehensive manual.

**Comment by mirabilos** [comment]
Hubert Kario dixit:

>Using `-m modulifile` just checks if primality certificates for the
>primes in the moduli file exist. `-v -m modulifile` also verifies the
>primality certificates. You need to do the latter if you don't trust
>the source of the primality certificates (haven't verified those
>primality certificates yourself).

Ah. So -m checks the moduli against the existing primality certificates,
while -v -m does that AND checks the primality certificates encountered.

>If you generated the primality certificates with Primo, it's much
>quicker to use `parallel` to verify them that to use `-v`, so that's
>why it's not explained in the README.

Right, it is. On the other hand, -v -m will also verify those that are
already present in the repo. Understood.

Thanks,
//mirabilos
-- 
/⁀\ The UTF-8 Ribbon
╲ ╱ Campaign against
 ╳  HTML eMail! Also,
╱ ╲ header encryption!
